### ISSUE TITLE
Unable to launch through GameList

### ISSUE THREAD

**Issue by valterooni** [game-list/game-list#105]
A most welcome concept and I thank you for this. Although at the moment, I seem to be unable to launch the games through GameList. Through the little lightning icon. Nothing happens, while running the exe directly from the game folder works fine. These are ren'py games. Any ideas as to what might be the solution?

**Comment by game-list** [comment]
Have you an antivirus? If you once launched a game that was detected as a virus, Gl will be marked as a virus too because it launched the corrupted file.

**Comment by valterooni** [comment]
Yes I have Windows Antivirus/Security/Defender or whatever else it's called, since it's not possible to remove it, or so I hear. I have however disabled it in Group Policies and the Real-Time Protection is also off.

**Comment by CuddleBear92** [comment]
@valterooni is this still an issue? 
Was it something wrong with the mappings? 
Did you use the install feature?

**Comment by valterooni** [comment]
After getting your reply, i decided to download the latest version and try it again, and it is working properly. Thank you for your time

**Comment by game-list** [comment]
great to hear, so I close the issue
