### ISSUE TITLE
Newly installed version of game that has older version overwrites executable path of older version and is not added to list of versions

### ISSUE THREAD

**Issue by matjojo** [game-list/game-list#114]
Version `2.17.16.8`

In steps:
1. install a version of a game.
2. Install another version of that game.
2.1 Do not select the replace option.
3. See that there is only one version.
3.1 This is the version I already had installed.
3.2 Launching this version launches the newly installed version.

When I first installed the second version of the game there was never a window to select the executable. I had to close the game and then kill one of its background processes to retry. (This background process had the folder with the new version in it opened)

Not fixed by a restart of the client, nor by a restart of my pc.

**Comment by matjojo** [comment]
After some more investigating with cuddle I can confirm that this also happens in the currently newest alpha version, `2.17.17a4.10`. 

It appears to be the same issue as in #84

**Comment by game-list** [comment]
could you post your settings, so that I can test in the same configuration?

**Comment by matjojo** [comment]
Is there a way to give you an extract file of my settings? Or should I give you a screenshot of the six settings pages?

These are the settings in text:
- 25 games per page with adjust to screen turned on.
- do not use large thumbs
- no special launch options
- version `2.17.17a4.10`
- Always download images
- Source and base directory are both in the same base directory and drive.
- Save old versions is not ticked.
- Delete source, copy save. and keep HTML are all not ticked
- On update: Keep old version.
- No profile
- Default tags screen.
- No display options
- No Mods options

**Comment by game-list** [comment]
do you have the version number in your path?

**Comment by matjojo** [comment]
In the path to the base folder of that game the version number appears, yes, as well as for the other version of that game. They are `Part 1 v1.05` and `Part 2 v1.30`. Note that on windows paths are case-insensitive.

Those two folders are the base folders for the two versions of that game. The paths to them are somewhat long, but I have the 255+ character filename option turned on, so that should not be an issue on the windows side.

**Comment by CuddleBear92** [comment]
if this is the same issue as #84 then it had no issues at all with folder creation at all. but its rather the internal links and mappings that gets overwritten wrongly.
So you are left with the wrong versions installed. namely the last install is always match the name of the latest version. making having multiple versions impossible. but this seems to only happen on the 3rd install and forward. its fine on the first two version installs, but gets funky on the 3rd.

**Comment by game-list** [comment]
Thank you for the image, now I see where the bug might be.

**Comment by matjojo** [comment]
That is not completely the same issue as I have, since for me I the second version entry in the "Installed Versions" list never appears. But since they are so closely related it's very well possible that they could be related.

**Comment by CuddleBear92** [comment]
yeah, that is issue #84 at a minimum. once you have a version already installed, it will not respect whatever version you enter and just name it whatever the latest release is. If you where to install a 3rd or 4th version on that title in the image for example, you would still only have two versions in the list. 

I have seen it be buggy with these versions in the past aswell. Hard to say its related though, But some titles have 18...... 18 chapters in their damn series. making this bug a pain in the ass for sure no matter what.

**Comment by game-list** [comment]
is this bug still happening in the last alpha?

**Comment by matjojo** [comment]
Sadly, I don't have a good way to test this since I only know if this one game with this scenario and I don't want to lose my save game. My issue sounds so similar to cuddles that it could very well be fixed now. If you want to test, the game I had this with is the `Bad Manners` game (https://f95zone.to/threads/bad-manners-v1-40-1-skaz.10946/)
