### ISSUE TITLE
Corruption if computer crashes while updating database

### ISSUE THREAD

**Issue by johnmoney-code** [game-list/game-list#116]
Sometimes, I don't know why, but my computer will occasionally crash out in the first 5 minutes of operation, with a blank screen. It's rare enough and fast enough to handle that I generally ignore this problem, but this time GameList was booting up while this crash happened. Now, the program will start with an "Error loading parameters" box, followed by an "Update" box, which is replaced by the box shown below.
![](https://cdn.discordapp.com/attachments/773924907360190530/861665516099600414/unknown.png)

**Comment by game-list** [comment]
Hi, the Corrupted file is the index file of the Tags_Games.fic file.

You can try to delete the ndx file, but I'm not sure it will work.

Keep me updated if it doesn't work I'll find another way to fix it.

**Comment by CuddleBear92** [comment]
He tried deleting it, no luck. i gave him my own file and that didnt work either i believe. 
Though having mine in there forced a re-index?

Feel there really should be a way to repair these database files more easily. If it was SQLite and it was malformed then a simple clone command would have writen out the good non-corrupted parts allowing it to be atleast useable.

**Comment by johnmoney-code** [comment]
Deleting the Tags_Games.ndx file causes a crash with a "file not found" error, while using a borrowed file crashes with the same "index file is corrupted" error as above.

**Comment by game-list** [comment]
I see 2 solutions here : 
- I give you the utility to do it yourself : https://doc.windev.com/en-US/?3519002&name=wdoptimiseur_presentation
- You send me the Tag_games.fic file and I repair it.

I will search for a solution to fix these problems from GL itself.

**Comment by johnmoney-code** [comment]
https://files.catbox.moe/8oyyey.fic
Pls do for me, thank you

**Comment by game-list** [comment]
here it is : [https://files.catbox.moe/5mbhhu.ndx]

**Comment by johnmoney-code** [comment]
thanks mate!
