### ISSUE TITLE
Latest version on pc, does not load updates from fzone

### ISSUE THREAD

**Issue by Enrique3482** [game-list/game-list#117]
Hello first. I have a problem... When I want to start gl, it always looks for the updates first, right? Now when I start the program nothing happens. As if there are no updates from playing. I have had this problem for a few days now. But I don't feel like deleting everything and reinserting the games manually if there are updates again. Is there a solution for this problem?

PS:the program is mega brilliant

Best regards from Germany

**Comment by CuddleBear92** [comment]
The metadata server is down. @tid needs to restart it manually, nothing is wrong with the client. You don't get data directly from F95.... yet. Maybe someday in the future once GLDev got some time to do so dev work.
