### ISSUE TITLE
drag and drop option for installation window

### ISSUE THREAD

**Issue by CuddleBear92** [game-list/game-list#120]
The Install Window, this one:
![image](https://user-images.githubusercontent.com/8496821/135352895-4c592e02-e86c-4e03-9b6b-e30bb24cfa1e.png)

Should have a button or a field to allow dropping in either both archives or folders. 
In a workflow i would want to be able to drag and drop a folder or zip sorted by filesize into the client for the install.
This should give it the path as normal, you just skip the selection step and would speed up things for the user.

I would either add another button in the same size that does the drop action. or make a new one UNDER all of the current buttons that is the same Height and covers the entire window size

![image](https://user-images.githubusercontent.com/8496821/135353285-165a8d0b-49d4-46b1-84a6-9a9336a799b2.png)

**Comment by game-list** [comment]
I've started working on it : you can drop files/folders on the buttons.

**Comment by CuddleBear92** [comment]
this was added, ill add another issue for expanding this request.
closing caused filled
