### ISSUE TITLE
Top panel is sometimes not interactable

### ISSUE THREAD

**Issue by CuddleBear92** [game-list/game-list#121]
The Top panel is sometimes not interactable. 
The Panel with the query field, and checkboxes for favs, updates, finished states. 

Both me and John on the Discord have had this issue in the last 24h on v2.17.17.10.
Restarting the client fixed it, not sure what the cause is yet.

John couldn't fill any queries, personally didn't try that as i only wanted to check some boxes that didn't work.

**Comment by game-list** [comment]
it seems to be fixed, can you confirm?

**Comment by CuddleBear92** [comment]
have personally not experienced it since that release. guess we can close it for now. re-open if its false i guess.
