### ISSUE TITLE
can not start the gl launcher comes error message

### ISSUE THREAD

**Issue by Enrique3482** [game-list/game-list#122]
I started the program this morning normally as usual and then these error messages came up.

does that mean I have to reinstall the whole thing or copy it to the default folder ?

have almost 200 games on it 

greetings to germany

(The <D:\GameList\tid\Games.ftx> index file is corrupted. Reindex your file.

Call stack:
Initialisation de LIB_GameNumber (FEN_GameList.LIB_GameNumber), line 1

Date: 20/11/2021 09:21:55
Project: Game List (2.17.17.10)

Additional information:
Error code: 70052
WD55 error code: 52
Module: wd260hf64.dll (01F260100j - 26.0.313.0)

Debugging information:
IEWDHF=7.6
Module=<WDHF>
Version=<26.0.313.0>
Fonction (7,58)
EIT_SRCFILE : <D:\GameList\tid\Games.ftx>
EIT_PATHNDX : <D:\GameList\tid\Games.ftx>
EIT_LOGICALTABLENAME : <Games>
EIT_TYPE_WDFILE : <2>
EIT_IDCODE : <14>     )

![2021-11-20 09_10_25-Game List](https://user-images.githubusercontent.com/66011833/142719536-4c49e350-a9f7-465b-beb8-3a59e2ce835c.png)
![2021-11-20 09_10_38-Game List](https://user-images.githubusercontent.com/66011833/142719538-ee722126-ff88-49cc-8e79-60de22ca929f.png)
![2021-11-20 09_11_20-Game List](https://user-images.githubusercontent.com/66011833/142719540-f525e665-155a-450c-b005-aa696241d544.png)

**Comment by game-list** [comment]
Hello,
What is the size of this mmo file? If it's not too heavy you can send it to me (MMO + fic + ndx files) so that I try to repair it.
I'll also add a function to repair MMO files in the next version.

**Comment by game-list** [comment]
Update : I have made the update but in order to test it I'll appreciate it if you send me the files.

**Comment by Enrique3482** [comment]
which files do you need specifically?? the ones from tid folder or which ones do you mean ?

**Comment by game-list** [comment]
games.* in D:\GameList\tid\ 
Games.fic
Games.ftx
Games.mmo
Games.ndx

You can zip them et send them to whatever file hosting you want.

**Comment by Enrique3482** [comment]
[Games.zip](https://github.com/game-list/game-list/files/7590118/Games.zip)
I hope these are the right ones

**Comment by game-list** [comment]
try this : 
https://github.com/game-list/game-list/blob/master/Games.zip

**Comment by ZeR0cOoLX82** [comment]
so from the feeling the updates run a little faster and yes it worked you are a god thank you very much

**Comment by game-list** [comment]
You're welcome ;)
