### ISSUE TITLE
Searching by tag in Table view throws non-fatal error

### ISSUE THREAD

**Issue by json-by-jason** [game-list/game-list#123]
version 2.17.18a2.11, latest alpha
attempting to add a tag in "search by tag" in the Table view returns an error dialog box, as shown in this screenshot:
[https://cdn.discordapp.com/attachments/773924907360190530/913243466186776586/unknown.png](url)
It seems to be something with "Date Last Played," but the tag search works fine in Owned view.

**Comment by game-list** [comment]
Fixed in version 2.17.18a3.11
