### ISSUE TITLE
Tag Rating window isn't a real window!

### ISSUE THREAD

**Issue by CuddleBear92** [game-list/game-list#22]
Two issues here, the Tag Rating window is not a real window so you can't alt+tab too it.

It does not spawn on seemingly any screen if the client is on a different screen than your main.
This means it has a window you can't see or can interact with. 
And you can't use the client at all. 
The only choice left is to kill the process in task manager.

**Comment by game-list** [comment]
It's a modal window, but I think that for some reasons it opened outside of the screen. So you can't close it with your mouse (you can press esc to close it).
I'll make sure it open somewhere where you can see it.

**Comment by CuddleBear92** [comment]
hmmm might be the case that you can close it with esc. won't work if you click the main window atleast. even alt+f4 won't work then.

If there is a window over the main client and you want to lock interactions with the main window. clicking the main window should highlight/select the overlaying window if possible.
