### ISSUE TITLE
newly installed versions is not listed in installed versions list

### ISSUE THREAD

**Issue by CuddleBear92** [game-list/game-list#52]
Newly installed versions is not listed in installed versions list anymore.
This makes it inconsistent and some users have found it weird.

Think if you have that list then all versions should prob be listed there, also the newest version.
The newest/current install should prob have an icon on its line.

![game_list_H8NepUHMwN](https://user-images.githubusercontent.com/8496821/81410961-e8a12c80-9141-11ea-8a27-0b57e6d717da.png)

EDIT: swapped out the image for a censored one.

**Comment by game-list** [comment]
It's worst then that, I'm not sure what it does when you click delete olde version. I'll work on this whole part of code.

**Comment by CuddleBear92** [comment]
Not sure why this is closed as this is still present in the latest version.

**Comment by CuddleBear92** [comment]
This might be directly tied to the delete option as every time i DON'T delete the last version then the version is listed in the list.

When i DO Delete the last version then its not listed at all.

**Comment by game-list** [comment]
Ok I'll check if there is a side effect with the delete last version.

**Comment by CuddleBear92** [comment]
I believe this one is fixed now in the last release of v2.17.7.7

Please verify this and close the issue if you believe its a decent fix @game-list
