### ISSUE TITLE
program crashes

### ISSUE THREAD

**Issue by Enrique3482** [game-list/game-list#57]
hi there,the program on is really super simple. but when i jump to stats for example he gives me an error message in the attachment see what i mean 

- [ ] 

- [ ] [bugs.txt](https://github.com/game-list/game-list/files/4688311/bugs.txt)

**Comment by game-list** [comment]
It's strange your bug refers to the window that downloads updates. Did it happen after you tried to download one?

**Comment by Enrique3482** [comment]
no it happened when i opened the window. then i closed and restarted the program and then it worked again

**Comment by CuddleBear92** [comment]
@Enrique3482 is this issue still a thing? 
Closing the issue now to clean up. ill reopen it if its still an issue :)
