### ISSUE TITLE
error when viewing screenshots

### ISSUE THREAD

**Issue by CuddleBear92** [game-list/game-list#62]
Had a crash when viewing screenshots.

```
Error at line 22 of Procédure locale affiche process.
The imgTemp element has not been created.

----- Technical information -----

Project : Game List

WL call:
Process of 'Procédure locale affiche' (FEN_Image.PROCEDURE.affiche), line 22

What happened?
The imgTemp element has not been created.

Error code: 3301
Level: fatal error

Dump of the error of 'wd240vm64.dll' module (24.0.600.2).
Identifier of detailed information (.err): 3301
Additional information:
EIT_PILEWL :
Procédure locale affiche (FEN_Image.PROCEDURE.affiche), line 22
Clic sur BTN_Next (FEN_Image.BTN_Next), line 2
Roulette souris (WM_MOUSEWHEEL) sur FEN_Image (FEN_Image), line 3
EIT_DATEHEURE : 07/06/2020 00:44:48
EIT_TYPE_WDFILE : <2>
EIT_IDCODE : <458752>

Help

```

This happened when it tried to load an missing image.
![image](https://user-images.githubusercontent.com/8496821/83955921-829ae880-a858-11ea-9054-a6fad4c361e9.png)

Deleting or refreshing the images does not help.

Same way the thumbnail is displayed in #60 

This is from this title: https://f95zone.to/threads/complex-society-v0-18-2a-abrokena-productions.33579/

**Comment by game-list** [comment]
I've got a problem with https not working on the new server. I have found a way to fix this until a solve the certificate problem.

**Comment by game-list** [comment]
It is now fixed (server side)
