### ISSUE TITLE
Weird metadata crash happening.

### ISSUE THREAD

**Issue by CuddleBear92** [game-list/game-list#68]
There is a weird metadata update bug happening here.
Its related to having a wrong thumbnail on a title.

The title name and creator name is all being updated to the wrong thumbnail title.
This is corrected once the user set another thumbnail from the correct title. 

Unsure how big of a ramifiaction this might have for metadata if not handled correctly right away.

![game_list_PWrDj3t6FF](https://user-images.githubusercontent.com/8496821/84969527-2f0e8180-b119-11ea-828e-e45e7a54e0fb.png)

![game_list_0JTIVJOjCv](https://user-images.githubusercontent.com/8496821/84969535-32a20880-b119-11ea-855f-458f3a835e3a.png)

As you can see, Title, Creator name, Versions, Path and playstate is all changed between this.
But atleast its corrected once the correct thumbnail is selected.

**Comment by game-list** [comment]
Yes there is a problem with thumbs, I'm working on it.
It should be the F95 cover that is used, I'm fixing it.

There is another issue with screens, I store their address on my database but sometimes the image is deleted on F95 so I should find a way to remove them from my datas.

**Comment by CuddleBear92** [comment]
re-reading the reply you made back then. i think you might have missunderstood the issue here. 
Note that the gallery of screenshots is the same, its the same title/game but the thumbnail is wrong in one of the images. And the title, update version, path and the rest mirrors the wrong thumbnail.

If this is saved then the other title is practically corrupted in the client.

**Comment by CuddleBear92** [comment]
closing this issue as its no longer happening. reopen if this is wrong.
