### ISSUE TITLE
Does not show updates.

### ISSUE THREAD

**Issue by murphyface** [game-list/game-list#75]
Had the older version 2.16.17 or such, stopped showing any updates anywhere.  
Deleted, installed newest one, still doesn't update anything 3 days later despite F95 showing updates since.

**Comment by CuddleBear92** [comment]
you can get the newest release here: http://www.game-list.org/gamelist.zip

Everything should still be working well.
Going to close this issue as metadata and updates are still rolling in, this is an issue with the server move and out of dates clients not handling it correctly.
