### ISSUE TITLE
multiple errors when grabbing updates

### ISSUE THREAD

**Issue by CuddleBear92** [game-list/game-list#76]
I am getting multiple errors where when grabbing new updates from the metadata server.

This happened twice on different updates.
Seemingly it loaded it all? unsure.
![image](https://user-images.githubusercontent.com/8496821/86029079-fe8ce880-ba32-11ea-9a47-b8d469127d28.png)

**Comment by game-list** [comment]
It's server problem, I should move to a better one fast. 
I'll try to do it in July.

**Comment by CuddleBear92** [comment]
ahhh, closing the issue then :)

Will make an issue to make logs useful, not having an log to share with errors i kinda painful and could help you find weird issues.
