### ISSUE TITLE
versioning issue

### ISSUE THREAD

**Issue by TrueMadMotion** [game-list/game-list#87]
![GLVer](https://user-images.githubusercontent.com/69113413/89825728-53a13b80-db55-11ea-803d-eebace5d70b4.png)
As seen in the image the game seems to have issues with the versioning. it doesnt recognize the newest version 2.17.11.7 as the newest. he thinks 2.17.1.7 is the latest

**Comment by game-list** [comment]
it was an error server-side, it's fixed. 
Thanck you.
