### ISSUE TITLE
Missing game

### ISSUE THREAD

**Issue by Saikuya** [game-list/game-list#89]
Game "About It" missing from database https://f95zone.to/threads/about-it-v0-91-5-about_it.59066/, needs to be added it seems

**Comment by ChaosDMNS** [comment]
Not sure what your talking about.. it's there..

Either it's been added after you posted this.. or you need to type in 59066 under Tools in Preferences. and click the fix button.

But anywho.. this issue should be closed

**Comment by Saikuya** [comment]
It got added after my post, a couple weeks ago I believe.

**Comment by CuddleBear92** [comment]
closing the issue since it was added and we have a pinned issue for missing and outdated titles #61
