### ISSUE TITLE
My Cute Roommate is misidentified as Lovely Guests

### ISSUE THREAD

**Issue by Zarggg** [game-list/game-list#90]
Every time I try to add to my Owned list or edit the listing for My Cute Roommate (https://f95zone.to/threads/5405/), Game List shows it as Lovely Guests (https://f95zone.to/threads/696/) and will not recognize the directory I have assigned for that game. The GL_Infos.ini file does identify the game correctly, this issue is only seen in the program itself.

**Comment by abbada255** [comment]
Yep, it is buggy. Can you try this as workaround? Try to add another image, set it thumbnail and see if it is fixed.

**Comment by CuddleBear92** [comment]
duplicate, closing #68

**Comment by CuddleBear92** [comment]
@Zarggg note that the dev commented on it here: https://github.com/game-list/game-list/issues/68#issuecomment-645844834
